version: "3"
services: 
  kau-sw-business: 
    image: mysql:5.7.35 
    container_name: "kau-mysql" 
    ports:
      - "3316:3306" 
    restart: always
    environment: 
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "kau_sw_business"
      MYSQL_USER: "kau"
      MYSQL_PASSWORD: "123456"
    volumes:
      - ${PWD}/mysql:/var/lib/mysql 
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

# docker-compose up -d 명령으로 백그라운드에서 실행
# docker exec -i -t kau-mysql bash 명령으로 접속
