version: "3" # 파일 규격 버전
services: # 이 항목 밑에 실행하려는 컨테이너 들을 정의
  kau-sw-business: # 서비스 명
    image: mysql:latest # 사용할 이미지
    container_name: "kau-mysql" # 컨테이너 이름 설정
    ports:
      - "3316:3306" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    restart: always
    environment: # -e 옵션
      # MYSQL_ROOT_PASSWORD: "password"  # MYSQL 패스워드 설정 옵션
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "kau_sw_business"
      MYSQL_USER: "kau"
      MYSQL_PASSWORD: "123456"
    volumes:
      - ${PWD}/mysql:/var/lib/mysql # -v 옵션 (다렉토리 마운트 설정)
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

# docker-compose up -d 명령으로 백그라운드에서 실행
# docker exec -i -t kau-mysql bash 명령으로 접속
