name: Admin CD
on: 
  workflow_run:
    workflows: ["Admin CI"]
    types:
      - completed
  workflow_dispatch:
  
jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
     - name: Configure SSH
       run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/develop.key
          chmod 600 ~/.ssh/develop.key
          cat >>~/.ssh/config <<END
          Host deploy
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/develop.key
            StrictHostKeyChecking no
          END
       env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          
     - name: Run Install & Build
       run: ssh deploy 'cd ~/kau-sw-business/admin && git pull && npm ci && npm run build'
